# Generated by Django 2.0.1 on 2018-01-07 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('symbol', models.CharField(max_length=200)),
                ('open_cost', models.FloatField(null=True)),
                ('close_cost', models.FloatField(null=True)),
                ('low_cost', models.FloatField(null=True)),
                ('high_cost', models.FloatField(null=True)),
                ('volume_cost', models.IntegerField(null=True)),
            ],
        ),
    ]
