# Generated by Django 2.0.1 on 2018-01-07 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_archive', '0002_auto_20180107_1943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='volume_cost',
            field=models.FloatField(null=True),
        ),
    ]
