# Generated by Django 2.0.1 on 2018-01-07 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_archive', '0003_auto_20180107_2119'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('market_cap', models.FloatField(null=True)),
                ('sector', models.CharField(max_length=200)),
                ('industry', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'company_details',
            },
        ),
    ]
